/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginIndexRouteImport } from './routes/login.index'
import { Route as PortfolioSlugRouteImport } from './routes/portfolio.$slug'
import { Route as LoginMembroRouteImport } from './routes/login.membro'
import { Route as LoginClienteRouteImport } from './routes/login.cliente'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated.admin'
import { Route as AuthenticatedAdminUsuariosRouteImport } from './routes/_authenticated.admin.usuarios'
import { Route as AuthenticatedAdminPortfolioRouteImport } from './routes/_authenticated.admin.portfolio'
import { Route as AuthenticatedAdminCrmRouteImport } from './routes/_authenticated.admin.crm'
import { Route as AuthenticatedAdminPortfolioIdRouteImport } from './routes/_authenticated.admin.portfolio.$id'
import { Route as AuthenticatedAdminCrmObrasObraIdRouteImport } from './routes/_authenticated.admin.crm.obras.$obraId'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioSlugRoute = PortfolioSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => PortfolioRoute,
} as any)
const LoginMembroRoute = LoginMembroRouteImport.update({
  id: '/login/membro',
  path: '/login/membro',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginClienteRoute = LoginClienteRouteImport.update({
  id: '/login/cliente',
  path: '/login/cliente',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminUsuariosRoute =
  AuthenticatedAdminUsuariosRouteImport.update({
    id: '/usuarios',
    path: '/usuarios',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPortfolioRoute =
  AuthenticatedAdminPortfolioRouteImport.update({
    id: '/portfolio',
    path: '/portfolio',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCrmRoute = AuthenticatedAdminCrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminPortfolioIdRoute =
  AuthenticatedAdminPortfolioIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAdminPortfolioRoute,
  } as any)
const AuthenticatedAdminCrmObrasObraIdRoute =
  AuthenticatedAdminCrmObrasObraIdRouteImport.update({
    id: '/obras/$obraId',
    path: '/obras/$obraId',
    getParentRoute: () => AuthenticatedAdminCrmRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/portfolio': typeof PortfolioRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/login/cliente': typeof LoginClienteRoute
  '/login/membro': typeof LoginMembroRoute
  '/portfolio/$slug': typeof PortfolioSlugRoute
  '/login/': typeof LoginIndexRoute
  '/admin/crm': typeof AuthenticatedAdminCrmRouteWithChildren
  '/admin/portfolio': typeof AuthenticatedAdminPortfolioRouteWithChildren
  '/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/admin/portfolio/$id': typeof AuthenticatedAdminPortfolioIdRoute
  '/admin/crm/obras/$obraId': typeof AuthenticatedAdminCrmObrasObraIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/portfolio': typeof PortfolioRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/login/cliente': typeof LoginClienteRoute
  '/login/membro': typeof LoginMembroRoute
  '/portfolio/$slug': typeof PortfolioSlugRoute
  '/login': typeof LoginIndexRoute
  '/admin/crm': typeof AuthenticatedAdminCrmRouteWithChildren
  '/admin/portfolio': typeof AuthenticatedAdminPortfolioRouteWithChildren
  '/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/admin/portfolio/$id': typeof AuthenticatedAdminPortfolioIdRoute
  '/admin/crm/obras/$obraId': typeof AuthenticatedAdminCrmObrasObraIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/portfolio': typeof PortfolioRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/login/cliente': typeof LoginClienteRoute
  '/login/membro': typeof LoginMembroRoute
  '/portfolio/$slug': typeof PortfolioSlugRoute
  '/login/': typeof LoginIndexRoute
  '/_authenticated/admin/crm': typeof AuthenticatedAdminCrmRouteWithChildren
  '/_authenticated/admin/portfolio': typeof AuthenticatedAdminPortfolioRouteWithChildren
  '/_authenticated/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/_authenticated/admin/portfolio/$id': typeof AuthenticatedAdminPortfolioIdRoute
  '/_authenticated/admin/crm/obras/$obraId': typeof AuthenticatedAdminCrmObrasObraIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/portfolio'
    | '/reset-password'
    | '/admin'
    | '/login/cliente'
    | '/login/membro'
    | '/portfolio/$slug'
    | '/login/'
    | '/admin/crm'
    | '/admin/portfolio'
    | '/admin/usuarios'
    | '/admin/portfolio/$id'
    | '/admin/crm/obras/$obraId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/portfolio'
    | '/reset-password'
    | '/admin'
    | '/login/cliente'
    | '/login/membro'
    | '/portfolio/$slug'
    | '/login'
    | '/admin/crm'
    | '/admin/portfolio'
    | '/admin/usuarios'
    | '/admin/portfolio/$id'
    | '/admin/crm/obras/$obraId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/portfolio'
    | '/reset-password'
    | '/_authenticated/admin'
    | '/login/cliente'
    | '/login/membro'
    | '/portfolio/$slug'
    | '/login/'
    | '/_authenticated/admin/crm'
    | '/_authenticated/admin/portfolio'
    | '/_authenticated/admin/usuarios'
    | '/_authenticated/admin/portfolio/$id'
    | '/_authenticated/admin/crm/obras/$obraId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  PortfolioRoute: typeof PortfolioRouteWithChildren
  ResetPasswordRoute: typeof ResetPasswordRoute
  LoginClienteRoute: typeof LoginClienteRoute
  LoginMembroRoute: typeof LoginMembroRoute
  LoginIndexRoute: typeof LoginIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio/$slug': {
      id: '/portfolio/$slug'
      path: '/$slug'
      fullPath: '/portfolio/$slug'
      preLoaderRoute: typeof PortfolioSlugRouteImport
      parentRoute: typeof PortfolioRoute
    }
    '/login/membro': {
      id: '/login/membro'
      path: '/login/membro'
      fullPath: '/login/membro'
      preLoaderRoute: typeof LoginMembroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/cliente': {
      id: '/login/cliente'
      path: '/login/cliente'
      fullPath: '/login/cliente'
      preLoaderRoute: typeof LoginClienteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/usuarios': {
      id: '/_authenticated/admin/usuarios'
      path: '/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AuthenticatedAdminUsuariosRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/portfolio': {
      id: '/_authenticated/admin/portfolio'
      path: '/portfolio'
      fullPath: '/admin/portfolio'
      preLoaderRoute: typeof AuthenticatedAdminPortfolioRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/crm': {
      id: '/_authenticated/admin/crm'
      path: '/crm'
      fullPath: '/admin/crm'
      preLoaderRoute: typeof AuthenticatedAdminCrmRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/portfolio/$id': {
      id: '/_authenticated/admin/portfolio/$id'
      path: '/$id'
      fullPath: '/admin/portfolio/$id'
      preLoaderRoute: typeof AuthenticatedAdminPortfolioIdRouteImport
      parentRoute: typeof AuthenticatedAdminPortfolioRoute
    }
    '/_authenticated/admin/crm/obras/$obraId': {
      id: '/_authenticated/admin/crm/obras/$obraId'
      path: '/obras/$obraId'
      fullPath: '/admin/crm/obras/$obraId'
      preLoaderRoute: typeof AuthenticatedAdminCrmObrasObraIdRouteImport
      parentRoute: typeof AuthenticatedAdminCrmRoute
    }
  }
}

interface AuthenticatedAdminCrmRouteChildren {
  AuthenticatedAdminCrmObrasObraIdRoute: typeof AuthenticatedAdminCrmObrasObraIdRoute
}

const AuthenticatedAdminCrmRouteChildren: AuthenticatedAdminCrmRouteChildren = {
  AuthenticatedAdminCrmObrasObraIdRoute: AuthenticatedAdminCrmObrasObraIdRoute,
}

const AuthenticatedAdminCrmRouteWithChildren =
  AuthenticatedAdminCrmRoute._addFileChildren(
    AuthenticatedAdminCrmRouteChildren,
  )

interface AuthenticatedAdminPortfolioRouteChildren {
  AuthenticatedAdminPortfolioIdRoute: typeof AuthenticatedAdminPortfolioIdRoute
}

const AuthenticatedAdminPortfolioRouteChildren: AuthenticatedAdminPortfolioRouteChildren =
  {
    AuthenticatedAdminPortfolioIdRoute: AuthenticatedAdminPortfolioIdRoute,
  }

const AuthenticatedAdminPortfolioRouteWithChildren =
  AuthenticatedAdminPortfolioRoute._addFileChildren(
    AuthenticatedAdminPortfolioRouteChildren,
  )

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminCrmRoute: typeof AuthenticatedAdminCrmRouteWithChildren
  AuthenticatedAdminPortfolioRoute: typeof AuthenticatedAdminPortfolioRouteWithChildren
  AuthenticatedAdminUsuariosRoute: typeof AuthenticatedAdminUsuariosRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminCrmRoute: AuthenticatedAdminCrmRouteWithChildren,
  AuthenticatedAdminPortfolioRoute:
    AuthenticatedAdminPortfolioRouteWithChildren,
  AuthenticatedAdminUsuariosRoute: AuthenticatedAdminUsuariosRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface PortfolioRouteChildren {
  PortfolioSlugRoute: typeof PortfolioSlugRoute
}

const PortfolioRouteChildren: PortfolioRouteChildren = {
  PortfolioSlugRoute: PortfolioSlugRoute,
}

const PortfolioRouteWithChildren = PortfolioRoute._addFileChildren(
  PortfolioRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  PortfolioRoute: PortfolioRouteWithChildren,
  ResetPasswordRoute: ResetPasswordRoute,
  LoginClienteRoute: LoginClienteRoute,
  LoginMembroRoute: LoginMembroRoute,
  LoginIndexRoute: LoginIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
